project:
  type: website  
  output-dir: docs  

website:
  title: "Welcome"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - blog.qmd
      - about.qmd  

format:
  html:
    from: markdown+emoji
    theme: minty # https://quarto.org/docs/output-formats/html-themes.html
    css: styles.css
    toc: true

editor: visual
