project:
  type: website  
  output-dir: docs  

website:
  title: "Welcome"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmd
      - blog.qmd
      - about.qmd  

format:
  html:
    from: markdown+emoji
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
