project:
  type: website
  output-dir: docs

website:
  title: "Electrical Engineer & Data Scientist"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - blog.qmd     

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
