project:
  type: website  
  output-dir: docs  

website:
  title: "Welcome"
  favicon: ./imgs/favicon-32x32.png
  page-footer:     
    left: | 
      © 2023 J. Thomas
    background: "#78C2AD" 

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About
 
format:
  html:
    from: markdown+emoji
    theme: minty # https://quarto.org/docs/output-formats/html-themes.html
    css: styles.css
    toc: true

editor: visual
bibliography: mypapers.bib
csl: ieee-csl-file.csl